export const COMPONENT_CONTROL_BASIC = 'ControlBasic';
export const COMPONENT_CONTROL_STATE = 'ControlState';
export const COMPONENT_DESTRUCT_BASIC = 'DestructBasic';
export const COMPONENT_DESTRUCT_STATE = 'DestructState';
export const COMPONENT_DESTRUCT_COLLECTION = 'DestructCollect';
export const COMPONENT_LIST_BASIC = 'LoopBasic';
export const COMPONENT_LIST_STATE = 'LoopState';
export const COMPONENT_LIST_COLLECTION = 'LoopCollect';
export const COMPONENT_CHILDREN = 'Children';
export const COMPONENT_SLOT = 'Slot';
export const COMPONENT_COMPONENT = 'Component';

export const DEFAULT_COMPONENT_SET = [
    COMPONENT_CHILDREN,
    COMPONENT_SLOT,
    COMPONENT_COMPONENT,
    COMPONENT_CONTROL_BASIC,
    COMPONENT_CONTROL_STATE,
    COMPONENT_DESTRUCT_BASIC,
    COMPONENT_DESTRUCT_STATE,
    COMPONENT_DESTRUCT_COLLECTION,
    COMPONENT_LIST_BASIC,
    COMPONENT_LIST_STATE,
    COMPONENT_LIST_COLLECTION
];
