import {
    COMPONENT_CHILDREN,
    COMPONENT_SLOT,
    COMPONENT_COMPONENT,
    COMPONENT_BASIC_IF,
    COMPONENT_BASIC_DESTRUCT,
    COMPONENT_BASIC_FOREACH,
    PROP_CONTROL_LIST,
    PROP_CONTROL_OBJECT,
    PROP_CONTROL_VALUE
} from '../common/constants';

export const BINDER_STATE = 'state';
export const BINDER_COLLECTION = 'collect';

export const PROP_STATE_VALUE = BINDER_STATE + ':' + PROP_CONTROL_VALUE;
export const PROP_STATE_OBJECT = BINDER_STATE + ':' + PROP_CONTROL_OBJECT;
export const PROP_STATE_LIST = BINDER_STATE + ':' + PROP_CONTROL_LIST;
export const PROP_COLLECTION_OBJECT = BINDER_COLLECTION + ':' + PROP_CONTROL_OBJECT;
export const PROP_COLLECTION_LIST = BINDER_COLLECTION + ':' + PROP_CONTROL_LIST;

export const COMPONENT_STATE_IF = 'StateIf';
export const COMPONENT_STATE_DESTRUCT = 'StateDestruct';
export const COMPONENT_STATE_FOREACH = 'StateForeach';
export const COMPONENT_COLLECTION_DESTRUCT = 'CollectionDestruct';
export const COMPONENT_COLLECTION_FOREACH = 'CollectionForeach';

export const BASIC_COMPONENT_SET = [
    COMPONENT_CHILDREN,
    COMPONENT_SLOT,
    COMPONENT_COMPONENT,
    COMPONENT_BASIC_IF,
    COMPONENT_BASIC_DESTRUCT,
    COMPONENT_BASIC_FOREACH
];

export const DOM_COMPONENT_SET = [
    COMPONENT_STATE_IF,
    COMPONENT_STATE_DESTRUCT,
    COMPONENT_STATE_FOREACH,
    COMPONENT_COLLECTION_DESTRUCT,
    COMPONENT_COLLECTION_FOREACH
];
